// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ContactRequest defines model for ContactRequest.
type ContactRequest struct {
	Email   openapi_types.Email `json:"email"`
	Message string              `json:"message"`
	Name    string              `json:"name"`
	Subject *string             `json:"subject,omitempty"`
}

// Experience defines model for Experience.
type Experience struct {
	Company     string    `json:"company"`
	Description *[]string `json:"description,omitempty"`
	End         *string   `json:"end,omitempty"`
	Id          string    `json:"id"`
	Location    *string   `json:"location,omitempty"`
	Order       *int      `json:"order,omitempty"`
	Role        string    `json:"role"`
	Start       string    `json:"start"`
	Tags        *[]string `json:"tags,omitempty"`
	Url         *string   `json:"url,omitempty"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// Project defines model for Project.
type Project struct {
	Contributors *string   `json:"contributors,omitempty"`
	Details      *[]string `json:"details,omitempty"`
	Id           string    `json:"id"`
	Image        *string   `json:"image,omitempty"`
	Links        struct {
		Demo *string `json:"demo,omitempty"`
		Repo *string `json:"repo,omitempty"`
	} `json:"links"`
	Order   *int     `json:"order,omitempty"`
	Slug    string   `json:"slug"`
	Stack   []string `json:"stack"`
	Summary string   `json:"summary"`
	Title   string   `json:"title"`
}

// SkillCategory defines model for SkillCategory.
type SkillCategory struct {
	Id    string       `json:"id"`
	Items *[]SkillItem `json:"items,omitempty"`
	Order *int         `json:"order,omitempty"`
	Title string       `json:"title"`
}

// SkillItem defines model for SkillItem.
type SkillItem struct {
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Level       string  `json:"level"`
	Name        string  `json:"name"`
}

// PostContactJSONRequestBody defines body for PostContact for application/json ContentType.
type PostContactJSONRequestBody = ContactRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit contact form
	// (POST /contact)
	PostContact(c *gin.Context)
	// Get work experience list
	// (GET /experience)
	GetExperience(c *gin.Context)
	// Get all portfolio projects
	// (GET /projects)
	GetProjects(c *gin.Context)
	// Get skills categorized
	// (GET /skills)
	GetSkills(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostContact operation middleware
func (siw *ServerInterfaceWrapper) PostContact(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostContact(c)
}

// GetExperience operation middleware
func (siw *ServerInterfaceWrapper) GetExperience(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetExperience(c)
}

// GetProjects operation middleware
func (siw *ServerInterfaceWrapper) GetProjects(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjects(c)
}

// GetSkills operation middleware
func (siw *ServerInterfaceWrapper) GetSkills(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSkills(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/contact", wrapper.PostContact)
	router.GET(options.BaseURL+"/experience", wrapper.GetExperience)
	router.GET(options.BaseURL+"/projects", wrapper.GetProjects)
	router.GET(options.BaseURL+"/skills", wrapper.GetSkills)
}
